// Test the thinking filter
const testResponse = `◁think▷Hmm, it looks like there was a typo in the previous response. Let me correct that. The user is asking what I just said, which probably means the initial response was incomplete or had an error. Looking back, the original response started with "Hello Steve! Bridvia is here to connect you with the opportunities that" but didn't finish the sentence. That's definitely a mistake. So the correct approach is to provide a complete and properly formatted answer. Let me restructure the response. The goal is to explain how Bridvia can help Steve. The platform's main service is BridviaConnect, which focuses on internships. So the assistant should mention that Bridvia offers structured internship programs through BridviaConnect. These internships provide practical experience, mentorship, and career development support. They help bridge the gap between education and industry, which can be beneficial for recent graduates, career switchers, or anyone looking to gain hands-on experience. The assistant should also highlight the key benefits like real-world projects, networking, and increased employability. Additionally, they should encourage Steve to explore the available internships on the platform or contact info@bridvia.com for more specific information. So the corrected response would be: "Hello Steve! Bridvia is here to connect you with the opportunities that matter. Through BridviaConnect, we offer structured internship programs that provide hands-on experience, mentorship, and career development support. These internships help bridge the gap between education and industry, giving you practical skills, real-world projects, and networking opportunities to boost your career. Explore our available internships or contact info@bridvia.com to learn more about how we can help you today!" ◁/think▷ Hello Steve! Bridvia is here to connect you with the opportunities that matter. Through BridviaConnect, we offer structured internship programs that provide hands-on experience, mentorship, and career development support. These internships help bridge the gap between education and industry, giving you practical skills, real-world projects, and networking opportunities to boost your career. Explore our available internships or contact info@bridvia.com to learn more about how we can help you today!`;

const filtered = testResponse.replace(/◁think▷.*?◁\/think▷/gs, '').trim();

console.log('🔧 Testing AI Response Filter...\n');
console.log('Original length:', testResponse.length);
console.log('Filtered length:', filtered.length);
console.log('\n📝 Filtered Response:');
console.log(filtered);
console.log('\n✅ Filter test completed!');